---

# Config for https://github.com/apps/release-drafter
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

exclude-labels:
  - 'skip-changelog'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Maintenance'
    label: 'chore'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

branches:
  - master

template: |
  ## What's Changed
  $CHANGES
