---

# Runs your workflow anytime the release event occurs
name: Release
on:
  release:
    types: [published]

jobs:

  docker_build_push:

    name: docker_build_push
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker publish
        uses: docker://pasientskyhosting/action-docker-build-push:latest
        with:
          image_name: pasientskyhosting/ps-pmacct
          build_only: 'false'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
